### ISSUE TITLE
Improve file upload handling

### ISSUE THREAD

**Issue by ConnorMac** [rehive/rehive-python#101]
Currently the file upload logic only allows the user to upload a single file and only in the `file` key. Ideally we should support:

- Multiple file uploads
- Custom file keys for each file
- File support for PUT and PATCH

**Comment by OdinsPlasmaRifle** [comment]
The way I suggest we resolve this is to update the SDK client to support file uploads on PATCH and PUT and have the file upload functionality trigger on fields that have a Fille object type (instead of a string).  As per this conversation:

>  ...So maybe a better way to do this `if 'file' in kwargs:` would be to check whether it is a `file` type object instead (rather than a specific field name).  So basically require the user to send a python file type object rather than a string. And then update `PATCH` and `PUT` in the same way.

**Comment by OdinsPlasmaRifle** [comment]
@almabud2 you can work on this issue as per my comment.
