### ISSUE TITLE
Handle non-json responses graciously

### ISSUE THREAD

**Issue by ConnorMac** [rehive/rehive-python#51]
Currently if a site 500s and sends back non json the SDK will throw `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` instead of parsing the HTML returned as the error string.

**Comment by ConnorMac** [comment]
`UnboundLocalError: local variable 'error_data' referenced before assignment` is thrown as well if the JSONDecode error fails.

**Comment by OdinsPlasmaRifle** [comment]
Duplicate of #72
