### ISSUE TITLE
Rename base_resource "function" argument

### ISSUE THREAD

**Issue by ConnorMac** [rehive/rehive-python#66]
Currently the first argument for base resource functions is the `function`. This build the last piece of the URL which is not obvious by the name chosen.

`id` may work but it will likely clash if we need to actually POST the `id` field. My immediate thoughts are to rename it `object_id` but whoever works on this can make a recommendation.

**Comment by OdinsPlasmaRifle** [comment]
Perhaps this should be `resource_id`. As an alternative to `object_id`. @ConnorMac

**Comment by OdinsPlasmaRifle** [comment]
This is referring to this class: https://github.com/rehive/rehive-python/blob/master/rehive/api/resources/base_resources.py#L9
