### ISSUE TITLE
Make status optional in AdminTransacton PATCH method

### ISSUE THREAD

**Issue by ConnorMac** [rehive/rehive-python#73]
Make status optional in AdminTransacton PATCH method

**Comment by OdinsPlasmaRifle** [comment]
If I understand this right, you should be able to just remove the `patch` method on `APIAdminTransactions` entirely right @ConnorMac ? I am not sure why this specific resource required `tx_code` to always be passed for all the CRUD functions?

@almabud2 basically we want to allow patches to be made even if they do not include the status (as other things can be patched as well). Checkin with @ConnorMac but my feeling is that the `patch` method is not required but I could be wrong.
